[package]
name = "zone-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance = "0.19.0"
serde = "1.0.145"
serde_json = "1.0.86"
crossterm = "0.25.0"
tui = "0.19.0"